### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by shafiuyushawu** [edubew/Ruby-Capstone#35]
Hello Reviewer,

This is @shafiuyushawu, @edubew and @Matthieu96Code. This is the link to the [Kanban board](https://github.com/edubew/Ruby-Capstone/projects/1)

# **Highlights** 
- We are in the group of three, @edubew assigned to `books`, @Matthieu96Code assigned to `musical album` and @shafiuyushawu `games`.

**Comment by DeliceLydia** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- All cards are created and assigned equally to each member of the team


### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
